src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 10, max: 255, minMessage: "Le titre doit faire au moins {{ limit }} caractères", 
    maxMessage: "Le titre ne peut pas faire plus de {{ limit }} caractères")]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAT = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?Category $Category = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?User $user = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAT(): ?\DateTimeInterface
    {
        return $this->createdAT;
    }

    public function setCreatedAT(\DateTimeInterface $createdAT): self
    {
        $this->createdAT = $createdAT;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Comment;
use App\Entity\Articles;
use App\Form\ArticleType;
use App\Form\MyCommentType;
use App\Repository\ArticlesRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\Persistence\ManagerRegistry as PersistenceManagerRegistry;


class BlogController extends AbstractController
{   
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }


    #[Route('/', name: 'app_blog')]
    public function index(ArticlesRepository $articlesRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $articles = $paginator->paginate($articlesRepository->findAll(),
        $request->query->getInt('page', 1),
        2
        );

        return $this->render('blog/index.html.twig', [
            'articles' => $articles
        ]);
    }

    #[Route('/article/new', name: 'article_new')]
    public function new(Request $request, PersistenceManagerRegistry $doctrine, FlashyNotifier $flashyNotifier): Response
    {
        $article = new Articles();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $article->setCreatedAT(new DateTime());
            $article->setImage("https://picsum.photos/seed/picsum/200/300");
            $article->setUser($this->security->getUser());
            $entityManager = $doctrine->getManager();
            $entityManager->persist($article);
            $entityManager->flush();
            $flashyNotifier->success('Article added successfully', 'http://your-awesome-link.com');

            return $this->redirectToRoute('article_show', [ 'id' => $article->getId() ]);
        }
        
        return $this->render('blog/new.html.twig', [
            'form' =>$form->createView()
        ]);
    }

    

    #[Route('/article/{id}/edit', name: 'article_edit')]
    public function edit(Request $request, Articles $article, PersistenceManagerRegistry $doctrine, FlashyNotifier $flashyNotifier): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManager = $doctrine->getManager();
            $entityManager->persist($article);
            $entityManager->flush();


            $flashyNotifier->success('Article modified successfully', 'http://your-awesome-link.com');
            return $this->redirectToRoute('article_show', [ 'id' => $article->getId() ]);
        }


        return $this->render('blog/edit.html.twig', [
            'editform' =>$form->createView()
        ]); 
    }



    #[Route('/article/{id}', name: 'article_show', methods: ["GET", "POST"] )]
    public function show(Articles $articles, Request $request, PersistenceManagerRegistry $doctrine, FlashyNotifier $flashyNotifier): Response
    {
        $comment = new Comment();
        $form = $this->createForm(MyCommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCreatedAt(new DateTime());
            $comment->setArticle($articles);
            $entityManager = $doctrine->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();
            $flashyNotifier->success('Comment created successfully', 'http://your-awesome-link.com');
            return $this->redirectToRoute('article_show', [ 'id' => $articles->getId() ]);
        }
        return $this->render('blog/show.html.twig', [
            'article' => $articles,
            'commentform' => $form->createView()

        ]); 
    }


 

  
    
}

templates/blog/edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme editform 'bootstrap_5_layout.html.twig' %}


{% block title %}edit{% endblock %}

{% block body %}
 <p>edit page</p>

{{ form_start(editform) }}
{{ form_widget(editform) }}

<button class="btn btn-success">Confirm and Save</button>

{{ form_end(editform) }}
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
<h3 class="mt-3 text-center">All blogs </h3>

{% for article in articles %}

    <section class="articles">
    <article> 
        <h2>{{ article.title }}</h2> 
        <div class="metadata">
            ma9al {{article.createdAt | date('d-m-Y')}} heure {{article.createdAt | date('H:i')}} 
            <p> {{ article.category.title }} </p>

        {% if article.user %} 
            <p class="text-danger"> by {{ article.user.firstName }} </p>
        {% endif %}


        </div>
        <div class="content">
            <img src="{{ article.image }}" alt="">
            <p>{{ article.content }}</p> 
            <a class="btn btn-info" href="{{ path('article_show', {'id' : article.id } ) }}">Read more</a>
        </div>
    </article>
</section>

{% endfor %}

<div class="navigation">
    {{ knp_pagination_render(articles) }}
</div>



{% endblock %}

templates/blog/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}


{% block title %}new Blog{% endblock %}

{% block body %}

<p> write a new blog </p>

{{ form_start(form) }}
{{ form_widget(form) }}
{# {{ form(form, {'attr': {'novalidate': 'novalidate'}}) }} #}
<button class="btn btn-primary" formnovalidate>Create</button>

{{ form_end(form) }}
{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig' %}
{% form_theme commentform 'bootstrap_5_layout.html.twig' %}



{% block title %}ma9al{% endblock %}

{% block body %}
    <h1 class="text-center">ma9al page</h1>

    <section class="articles">
        <article> 
            <h2> {{ article.title }} </h2>
            <div class="metadata">
               ma9al {{article.createdAt | date('d-m-Y')}} heure {{article.createdAt | date('H:i')}}
                <span class="text-danger"> {{ article.category.title }} </span> 
                <span class="text-success"> {{ article.comments | length}} comments </span> 
            </div>
            <div class="content">
                <img src="{{ article.image }}" alt="">
                <p>{{ article.content }}</p>
            </div>
        </article>
    </section>

    {% if app.user %}
        {% if app.user == article.user %}
            <a href="{{path('article_edit', {'id' : article.id} )}}" class="btn btn-success mt-2 mb-5" >Edit</a>
        {% endif %}
    {% endif %}
    

    <section id="comments">
        {% for comment in article.comments %}
            <div class="comment">
                <div class="row">
                    <div class="md-col-3 text-danger">
                            (<small> {{comment.createdAt | date('d-m-Y')}} heure {{comment.createdAt | date('H:i')}} </small>) {{comment.author}}
                    </div>
                </div>
                <p>{{comment.content}}</p>
            </div>
        {% endfor %}
    </section>

    <hr>

    <p>Comments</p>
    {% if not app.user %}
        <h2> you need to connect first </h2>
        <a class="btn btn-info" href="{{path('app_login')}}">log in</a>
    {% else %}
     <section>  
        <h2>add new comment</h2>
        {{ form_start(commentform) }}
            {{ form_widget(commentform) }}
            <button class="btn btn-primary" formnovalidate>add comment</button>
        {{ form_end(commentform) }}
    </section>
    {% endif %}
    

{% endblock %}